[2024-02-16T18:14:55.789+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: mlb_dag.player_lookup scheduled__2024-02-15T00:00:00+00:00 [queued]>
[2024-02-16T18:14:55.795+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: mlb_dag.player_lookup scheduled__2024-02-15T00:00:00+00:00 [queued]>
[2024-02-16T18:14:55.795+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2024-02-16T18:14:55.807+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): player_lookup> on 2024-02-15 00:00:00+00:00
[2024-02-16T18:14:55.813+0000] {standard_task_runner.py:60} INFO - Started process 96 to run task
[2024-02-16T18:14:55.815+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'mlb_dag', 'player_lookup', 'scheduled__2024-02-15T00:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/mlb_dag.py', '--cfg-path', '/tmp/tmpmbcffpi_']
[2024-02-16T18:14:55.816+0000] {standard_task_runner.py:88} INFO - Job 4: Subtask player_lookup
[2024-02-16T18:14:55.975+0000] {task_command.py:423} INFO - Running <TaskInstance: mlb_dag.player_lookup scheduled__2024-02-15T00:00:00+00:00 [running]> on host 9f908554d9a1
[2024-02-16T18:14:56.027+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='***@example.com' AIRFLOW_CTX_DAG_OWNER='troy' AIRFLOW_CTX_DAG_ID='mlb_dag' AIRFLOW_CTX_TASK_ID='player_lookup' AIRFLOW_CTX_EXECUTION_DATE='2024-02-15T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-02-15T00:00:00+00:00'
[2024-02-16T18:14:56.029+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/mlbapi.py", line 5, in player_lookup
    from pybaseball import  playerid_lookup
ModuleNotFoundError: No module named 'pybaseball'
[2024-02-16T18:14:56.037+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=mlb_dag, task_id=player_lookup, execution_date=20240215T000000, start_date=20240216T181455, end_date=20240216T181456
[2024-02-16T18:14:56.046+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 4 for task player_lookup (No module named 'pybaseball'; 96)
[2024-02-16T18:14:56.068+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-02-16T18:14:56.184+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-02-16T18:28:45.271+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: mlb_dag.player_lookup scheduled__2024-02-15T00:00:00+00:00 [queued]>
[2024-02-16T18:28:45.277+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: mlb_dag.player_lookup scheduled__2024-02-15T00:00:00+00:00 [queued]>
[2024-02-16T18:28:45.277+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2024-02-16T18:28:45.286+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): player_lookup> on 2024-02-15 00:00:00+00:00
[2024-02-16T18:28:45.291+0000] {standard_task_runner.py:60} INFO - Started process 69 to run task
[2024-02-16T18:28:45.293+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'mlb_dag', 'player_lookup', 'scheduled__2024-02-15T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/mlb_dag.py', '--cfg-path', '/tmp/tmpn64syah5']
[2024-02-16T18:28:45.294+0000] {standard_task_runner.py:88} INFO - Job 3: Subtask player_lookup
[2024-02-16T18:28:45.333+0000] {task_command.py:423} INFO - Running <TaskInstance: mlb_dag.player_lookup scheduled__2024-02-15T00:00:00+00:00 [running]> on host 3fb91e07d803
[2024-02-16T18:28:45.633+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='***@example.com' AIRFLOW_CTX_DAG_OWNER='troy' AIRFLOW_CTX_DAG_ID='mlb_dag' AIRFLOW_CTX_TASK_ID='player_lookup' AIRFLOW_CTX_EXECUTION_DATE='2024-02-15T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-02-15T00:00:00+00:00'
[2024-02-16T18:28:45.968+0000] {__init__.py:543} WARNING - Matplotlib created a temporary cache directory at /tmp/matplotlib-vb78l3_i because the default path (/home/airflow/.cache/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
[2024-02-16T18:28:46.121+0000] {font_manager.py:1578} INFO - generated new fontManager
[2024-02-16T18:28:46.382+0000] {logging_mixin.py:188} INFO - Gathering player lookup table. This may take a moment.
[2024-02-16T18:28:52.142+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-02-16T18:28:52.153+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=mlb_dag, task_id=player_lookup, execution_date=20240215T000000, start_date=20240216T182845, end_date=20240216T182852
[2024-02-16T18:28:52.199+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-02-16T18:28:52.213+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
